name: flutter_deep_linking
description: A Flutter sample showing off deep linking
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  nav_stack: ^0.0.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
